- title: User experience
  text: All Proxify developers are pre-vetted so you will have  a new team member ready to start in days. Not months.
  icon: connection

- title: Illustration work
  text: From big commissions to smaller projects such as illustrative icons, spot illustrations and so on.
  icon: visual

- title: Brand identity
  text: Working on giving a meaning to every client's specific need in order to shape the brand in consumers' minds.
  icon: pin